=== maxwai81/maxwai-interview-Personal-Agent/job-advisor-web/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Job Application",
  "description": "Form data for Job-Advisor-for-Job-Seekers subagent (cloud agents auto-invoke that subagent for job-fit flows; see AGENT_INSTRUCTIONS.md)",
  "type": "object",
  "required": ["company"],
  "properties": {
    "company": {
      "type": "string",
      "description": "Company name (required)"
    },
    "jobTitle": {
      "type": "string",
      "description": "Job title or role"
    },
    "jobUrl": {
      "type": "string",
      "format": "uri",
      "description": "Job posting URL"
    },
    "linkedinUrl": {
      "type": "string",
      "format": "uri",
      "description": "LinkedIn profile URL"
    },
    "location": {
      "type": "string",
      "description": "Location (city, remote, hybrid)"
    },
    "resumeBase64": {
      "type": "string",
      "description": "Resume file as base64 (PDF, DOCX, TXT)"
    },
    "resumeFilename": {
      "type": "string",
      "description": "Original resume filename"
    },
    "submittedAt": {
      "type": "string",
      "format": "date-time",
      "description": "ISO timestamp"
    }
  }
}

=== maxwai81/maxwai-interview-Personal-Agent/job-advisor-web/request.json
{
  "company": "ServiceNow",
  "jobTitle": "Director Solution Consulting Hong Kong",
  "location": "Hong Kong",
  "jobUrl": "https://www.linkedin.com/jobs/search/?currentJobId=4343828628&f_C=29352&originToLandingJobPostings=4343828628%2C4336039001%2C4369907204%2C4358491707&trk=d_flagship3_company_posts",
  "linkedinUrl": "https://www.linkedin.com/in/max-seto-pmp-75ab992b/",
  "resumeBase64": "JVBERi0xLjYNJeLjz9MNCjc5IDAgb2JqDTw8L0xpbmVhcml6ZWQgMS9MIDEyNDAyNS9PIDgxL0UgOTc3MjMvTiA3L1QgMTIzNjEzL0ggWyA1ODUgMzE2XT4+DWVuZG9iag0gICAgICAgICAgICAgICAgIA0xMDQgMCBvYmoNPDwvRGVjb2RlUGFybXM8PC9Db2x1bW5zIDUvUHJlZGljdG9yIDEyPj4vRmlsdGVyL0ZsYXRlRGVjb2RlL0lEWzw1M0QyNTMwN0IyMjFDQzAyRDgxODk2RTQ2REEwMUNDOT48QzMwRTMzNTcxNjE5NEE2M0I1MTAzQTE1NkExRkQ0RDQ+XS9JbmRleFs3OSA3MV0vSW5mbyA3OCAwIFIvTGVuZ3RoIDEyMC9QcmV2IDEyMzYxNC9Sb290IDgwIDAgUi9TaXplIDE1MC9UeXBlL1hSZWYvV1sxIDMgMV0+PnN0cmVhbQ0KaN5iYmRgEGBgYmBgLgWRDLEgkuk4iDRuBLNfgkiuDyCSMQhMaoBJPRDJrQYijZaDSJ1nINJjI9icKCDJ6PgRzI4Gq5wEItntwXpzwGQYiNRgBrPdwaQviGTtB5L/W9gYmIBuuwc2gYFxRJP/GZi+XwUIMAD6DRLbDWVuZHN0cmVhbQ1lbmRvYmoNc3RhcnR4cmVmDTANJSVFT0YNICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICANMTQ5IDAgb2JqDTw8L0ZpbHRlci9GbGF0ZURlY29kZS9JIDI2MC9MZW5ndGggMjI4L08gMjQ0L1MgMTY3Pj5zdHJlYW0NCmjeYmBgYAKiZQysDAysOxkEGRBAkIEFKMrCwLHyhAEPwy4BlhJH5oYJAnwb5EIYGG6/7Z0AU8iuZDVh6sZ1HJuCBV4EhR3b8XCfa6tir9cdmY7vRaITusWtRI4tzeNzbTftCGBwTevo6Ghg0ACSDELKGSCKgREspATEKh4gASC/Ac06IJBjYDytB6TFgVgKLBLGwM/06MQanhkzF8g3mDTkcF1IWrTOyeoGg4dwAqOrHNtLJh0GRtsMfgG5h3wO1Q03GJfwfIA6WZGB8aIYkGYE4h9ArMLA+GAPlP8MIMAAf89GEg1lbmRzdHJlYW0NZW5kb2JqDTgwIDAgb2JqDTw8L01ldGFkYXRhIDM0IDAgUi9OYW1lcyAxMDUgMCBSL091dGxpbmVzIDY5IDAgUi9QYWdlcyA3MiAwIFIvVHlwZS9DYXRhbG9nPj4NZW5kb2JqDTgxIDAgb2JqDTw8L0Fubm90cyAxMDYgMCBSL0NvbnRlbnRzIDg0IDAgUi9Dcm9wQm94WzAgMCA2MTIgNzkyXS9JRCAxNDggMCBSL01lZGlhQm94WzAgMCA2MTIgNzkyXS9QYXJlbnQgNzIgMCBSL1Jlc291cmNlczw8L0NvbG9yU3BhY2U8PC9DUzAgMTA4IDAgUi9DUzEgMTA4IDAgUj4+L0V4dEdTdGF0ZTw8L0dTMCAxMDkgMCBSL0dTMSAxMTAgMCBSL0dTMiAxMTEgMCBSL0dTMyAxMTIgMCBSPj4vRm9udDw8L0MwXzAgMTE2IDAgUi9DMl8wIDEyMSAwIFIvQzJfMSAxMjYgMCBSL0MyXzIgMTMxIDAgUi9DMl8zIDEzMyAwIFIvVFQwIDEzNSAwIFIvVFQxIDEzNyAwIFIvVFQyIDEzOCAwIFIvVFQzIDEzOSAwIFIvVFQ0IDE0MSAwIFI+Pi9Qcm9jU2V0Wy9QREYvVGV4dF0vU2hhZGluZzw8L1NoMCAxNDMgMCBSPj4vWE9iamVjdDw8L0ZtMCAxMDMgMCBSPj4+Pi9Sb3RhdGUgMC9UeXBlL1BhZ2U+Pg1lbmRvYmoNODIgMCBvYmoNPDwvRmlsdGVyL0ZsYXRlRGVjb2RlL0ZpcnN0IDQwNy9MZW5ndGggMTI4MzEvTiA0NC9UeXBlL09ialN0bT4+c3RyZWFtDQpo3uyby7Jkx3Wen8FP4DMkQwJ677ynQ8EwAIoigqTkIChS4YozaAEtsENgNwJo2uSDOPwCnnno1/DDeOjwyOv7V+auql1VXacbkMQBuyNP7trXzJUr/3Vfl/ywPKxLeQjVuvoQi3XtYV2tLf1h5fdqd5Rk/fqwNq6Fh7DyOz6EZNfsOOl6tp77y0NJ0fr6UIu/qwXu63zJ/vAjxR7syF6Z0mJ/g/1KmVtC5Khyzl6aGp8K2QaYuCcw1BS5Wu0oJ642jrp9OnQ7ainbwJeHtBSetXvtiLfGYEeVIceoIyZog19asfdFG/665KJJp7U0nqh21CpH7SGFDFlif7DvF0Zp34i1Mxv7RuzV3pfsGwmS2Aw5iszLvpECI7WR2ZGetW+kCKlT5ShxX+PIKPRXf/Xs0x9/9mDfXR5++ezvf/lzO04c/+hHB1bJjh7tno/0Gm75+PU3X7z45rDYj+Xx2S9ffP7mYBPLvX0IUdqHMdb8UNb1w/T47LPf/+ObP3794tnPX77652e/4uijV69ev7FXP/v0k08+fv7tiy8eep7f0A1//Yc3f/PZm+dvXjz7/PnD8mFcwo9+dPXaeuP88mG/9cSHi6589O3nL169eeg1PPvov3z5m5dfvPmtccuyPPvk+dc/ffHyy9++eWglPfvxC7/vgxDDs5989fzLbx/Ss5+8fvXm449f/+HwAczzgei7Vhh6iY+6+pOXX72ID92JxYm/ff47mzf/fvwX/+nlqy9/8vzVlz/92Qe/fPHl7796/s2zT988/+rl5x+9+vKrFw/Ls188/8MYULQBffbmxe9+ahyug18/1MVnxVsZ3Tcvv37z+ptn/zAGXVIzykJJKMtNb/nsJ7bqf/zWXvvpq396bY/8Hatqt/3g0y9s0i/f/PGHtrZfvvz2zTd//MFHX7z+xxc/tNX8+uuvXvwOmhghn/34N06189ForzL1ufb2Ie5g4CfDf/YbbWbx2dMG7MvxxXOjsN347QEMgHGe/fWrz19/Yfc/myP/4Kfbx8dXX//9q5d20wtbc41tG4Y+/s5TP/KQgUwWKV8YPzW9+8hENdQTJlrLFSYq9hCXDPUMd3jbYKLnv3v51R9/8Kvnv339u+c/3PgqPPR+zle//uhvPvn1T//Cb/zLj19/9YWuffbmmxdvPv/ts799/c3vnn+lU78Zg7IVO2c5563VdsPbmCvDXKcrdeXLZzwlUBZBPv3xr17/zac//sXzr7clus087RbzhFPmOSwHHjcECg8mGrrhn6GQ/W39odk7iqGpCYH+UNsKYD8iUAwuMyB94Cp3RWNV8J0+1/poIiH4swbuhurRdjeXo9+dDtlkTjeRUppBXDPZU0zu5Gpwlx+yfaka6FaTT8kAPdvwisFAruGh2QCriZla7ZzdT19NvBR7dbFxVQP6UmEAvs/LudEAhgHbyNTPeWUD4mxTK4b32SRTscHmnh5iCzouJisMNjX6skQdd3ue82Wtjza2lnRny4cEdiNNJUkX+5idNjFTFj5sH2KUNhA+TG+DeDSe5fON8S4HaMD85/xsLo8m2yTLGabJ8oMN8xFZzp5lqMhtZDRDMxF9sC8/SkAHREeV6F3HVAwItWA52D2IuFh8eWO158oj4hJB2QMicTmYgH1ESCIeIZUJxwOk68YaNr5HhOCanE3W7O8uedU76wLHQAn/RjahmaOee+jcZ2ODB4zVHqWnlOzvKWVjqroku2ZjgRZGfttY1qLTq6YD71oXu7mzzvSLEQx53hbx79pQfgJsa729oPnar7ZcLAm8kaKW5HHlfluuBHr09VCMV8p4L1zNO/TOwoNcWOHc/BhMEQpGfX4HG2UwvQyuDSbyw+IzDivNuTPYtrHVekQbC8YHUDYE2xH28hizOBk+gkfEM1CzwmaLBqyB5w7bPQY2mK0akwq821Yrq7dJo7pIy0pZJGVLwasMbvtIqc75sw9jxsXJnAd70rM92zoGM9hv9mxNWJA+9cX7VsXKsN6x187RlmXDzH4bD9DCBlohaPftnJat34gy+lyy3tmq716xFZsss+HWhzZYvNjzEGaFWp0XmdpmuqkDFmocEBd50pguGqmjPR1tr8cQDmxhjjeK7Km2o8bsJ8Uv+uIYUsEZNNjm2HKrBwC1Ir08RluFmJvjUe6HSfmblN5RfE/pPYX3vYBUODZ4zwiyEQIk6PH4EQa5PXB5MF+BGEkLOrxzm2n6h9KSnUNzX5xtTR8/6EYNNGmfpDUfKgQ01uosbUEiFC1/X5wQU6IYevgetUWdkgQpgnSYUgTgF9KyIJI+q7NedcnUF7+uZyVIurNXdMRl8Qp7rrKtgs4X5BzXFibbhIhcz2sUjfQOxmbPZqNXk0Baju/jnph1jvG3pYrNJR1ifEz6lo/J7KwDzLG6SLCjZqtTkZcFNhNSPQJbbEqokgzatGmGrFmXxFDKY+pcZCmNH3s78JJqayVSGXnOyKSHgz7SBk5yb5WxCEgaLNvATcQXVt2fWDH+6jpELuLZZELi2OQI26U1Nm16zHYts5mzsT4ya2FDJ9cPkm9yyRWtRtVGh61aa5K2bP6yol+Y9QDL2wAwL7NNLdvqdG1zF/Xafr3rvG2Lx2zfyLa9tO1se8HR3Wja4SRWZ4mOwIYf0JFn+yJgiVPYPeYWDs3YojBhG1Rdo52zyTV0zjyVAu5eDJt3OPu99zfQ6an9Do0ei4n6xf7afAuGQzGRjRSFhfMjPMFWYd1XkU9cY5oOMIvg4jcIhnXrnGUbFy6UROYe+8bcxDzb6gEvQjLpXUFVWKPDdbYUcGJpYiuWRJvJBHIF8WzjcN+U3CyhffexLsWvwbFLk6oCq9V1AVwe68rzSe+qqGNyiXDcDtfmkZZ4bQ4DdHzMc7zXxio0t/fqOVTKZX2sCemB1l8lqLqgtRrlUZqSMXBo5bFmqAuta7Exl6ECj91quxqQO1QAya7l5mOPDc1XEu2xGkDVNu5F7bbxRuPNahpSNA5eHo1/kTGPtWMosCPtFS7gF3Yn6G40M8TQ1R6azjzwNF+yH8gE21bjkqOwve6xLV0oVw0hm6F9Kog6IARPDE6dTOvtypmOLrhAVTP0msFuS3BgS64Wnkm+J/Zzx97rLySl7/C7/aa83epN9zKidDdyZKf0fFjRE1nwuBQn6uhBSBBo/t4oMim/XdgvCYvP1r24cHFirlQPfpGVMuvgsJ0HTZGhnI/x5HyWfPbz9cAXhb6jnyu9rXjCfEkICWaw4qS7fk6+RwOGbpzX8WtenGm2BRp6wY1eW1Fk7w7Fu9+TYZ3T4XN9Bw6eJ9i5HfE+mBFVwu1ayNYlcKopmng3hRQSQOliAdh9Ug3GUm5LqAP8jttCGC4I9673ZiZChiUEvZspHNgYdsCvUtxfbGbeTvubOC+8qkJz0ABt38zTdakS6JyFBA0w8U9IBtsoBVQ2/W5g1bOZURL/y6CrHazSntmdpp4IDnhvR/OAOnpvt4E17HhIxnttQiv+5VX63Or6hP2xb4E4wygugk87sMf12CqqZmwYxpyiBoFo5ztgPecM51GTMKOlaq7Sie0gHNDHkvHCwkW+gYmB2xrVZV0l5KxLB2QTXhJT9uxWuUjwNWuo0ZRyI7s0CqzbVeZF6noWM1nehyA5AGeYLLKbMp/LRWhsB1DEqFqKzK2Wul+QtoZZ7L79WvXS2g6ivWzftfmXDK8l+fC+4OkejpTpz5jKi1C1YdFLP11de5RIs2GW5QKmsMSBKpQ9tCz1w+CQ0eNw+mj0VIRAQwzBhngNh07RYG4T9Dkfsi0SJu2KPZv1OvgomOLUUXhDqoeAXpUSN6KFGeDwuWxrmeV9sAtZsQjXoO2gHPDhwLS2oMNekWEgHTrYrpEvOpSkVxmd7E+RWLSDenCYwc2C/yHYe0LWQTjsMfoWZl9u+LtQ/H2cmPC8RqaK6QtA20E6nFwiloJY9Evt5BL7BbvYL2EYHy/hDoQr/FI5vYRXCaNNl9Dnt0tyQsU5DNyCO0Hx1H4vUJ7aP13wfDdhdF/IvN+ZTTTNg0cbGQORSaLw1KpIF9IB0DVr+nCpTe0F2r3fT9HQ3u/MXpS+++9zUTt/3zq/8WKqiuoNNjUD+7DfrO/an0vzU83s7A7E/Dx4XPGTrnlFubYuHlZFVpdmAIfcXnNYdCmshxDkbLYL3ILI0QUzKJeFk4VfzU/2w9M4eM+nKJ5oM2Of2WsJ02YTC3II52LifboAUzkxPYtE3EU/HGay5EO/2z/VRCVigNP+wsF2p9872iQGlnjRn7o3r/Uo7F0K+3l/6ZS746Tb9WXSYdJl5za96Ua915+4Wa/195yCmzsWCK5966+4/DDkl3TsN2Pn3JG79azKWvSsoiZyy5oegEW+VpQ1ohOVrIIaZiwg6Fp+aGhiEMP+uKG2olSu8hki1KU+VjxvQb+4U9EKXkD4g2e6frE/qm3YBqPjKl4xw4veibyX1Zp5S+ZaFjLrJ0+butHB20pqAuysPIOa+YSMNp4h70KOOP+la2bJ6he6hQJBaDxVkY8aH3w2lS9Ud4SZ8rccmjx/tuvxKNsf476+csCNRqGmJxqf61F+LDtICuZopboZKR0lqgLKOO6wy+2gHkz1fLQDnbabWFu/ZiIFNreDYKqdQQjwoLyPtvoutIPCH3fJrx55WQcNlVzSgvtKV9yW9sc9pHbAW4J73OyAt2CA67tQoMX5BVaQVRcftKhr3fmgsYIY7eKDxgpihogPgP61KVbFNVaQtdR6IuzsTx7r2VjBxgqyni0rfNR9PVvhE6WNoZU+yMXiNawikYvFIx3FyVXTCbkq7x7RRjvgepuTae1A0AFcxVVjej3RrD5icf6yXscM8NiirNtl3JGadrGHOoZTX7I/1Bf+rIPo0qE7kVs+3NECwedmM+irbmzjMfy6eEG1HrhP7Y8HPu1Ap8q8VvnTtM9XXAUNx65dqqji+ApWXLL+Wj0R3Qm0diKOuPwI5zQjTofze3KLwg7yYSMF1mbA5F3oTA99u3l802wOi/FPWKK7s+3AtF0ss7YcRRbe6xjsVhuJ/XEzwg7KQZIM6ywPCTcCUDKoY9ni2KBjb2GTNFOquASBFdqIRni00AzaqMgVEDNh/wjdHmDdw/YIGJsyQ5gxTEC1cTeG20Y0HvM8YJ4DtnZA7LKHca1Ht1xz8egiFnqQk80vt4OrWmRWsT8Cm0GhB+7sQ6iuHnkkVt6OUcQpYjcR90QRIzG/82hvYaddXG0S9kKMKuhdPDx1PvL56Coq5LKJ5nte9L3qcCvetvX7eVUf06aSpPYYCFIHotSl6sB0uSkXZxD2nsbg8tVeZTcH4tEeX17Mtuq2pMGgIBCiZtJ2gEsocLrxy+MpQeHqsK7jJgN4hWcUlmE4I7JpHGlKlz1MtkcIy7g9EGFKrhfYprcTBLqHbA9BHwgeYbGDfkiZ7LtOcM+VsFLtoajoeJEaFRTnJnTrr4j9MONAEkOrnLD2EFs0kJCnpxOjyYsc9AHPgP1xDLMDY/V1xLqbQj34j+wVGULkrn1lg1ZGhdz2iteNnA7iejlnX5nOcAvfqmNbyScQahrUrNl90vif2MVacfsC/n4bWkIks91CY9QstB5rBZc6hps8D4pmRznAwGyplxgy+PwAG7z/eKgJHSKpq/e1uXRSJGMyCTC/pMcQ7YYQSS8huSeu+Pew8ghaKBQubNKnppeHPhih8AMExYJtUHYQSSFxf7e+guqGZCn6chHveICY1JEQWSHSHXCT2YHNlTTVhrIiHgAGyUFV/M4pD4YiiPEq6s41IhJX1i4qdKiAreI206cfRixn9GYA4drBx67IEckzbYQltgFMK4VEJuM8xodPkK4e8JLiLZVVpOOhojfPL5ojmW40Ao91dalcs5J4siKKaK85h5MkAvdxoTww1OlfQ3ijh85ewhphJGGpr3ikViHSwVtbP16iKG6uN5F0y1gYTrztA3M6E0Ln9I/9Dn/KcLjahpCev+u3WZVFpCkjcYOsTztpBE8lH/A14LLNSgpdhjoLRPfmsM8mquCh6VsBl23A+SqsS+3UxUFUbpGvZ8bgJPiJhxs2YGdbF/njOpId6A/5vfLstUNoxu+8wTAE1YnTholJ0sm+0OtMI7HbjAaBjGh8rwFrPSg8rTfbqgcQNIGI2f94qlPAUjdQSuNOMIpdzX6xA94Z27zGQPAksPHso64WdbeAI7AvtYBW+ZQNKjMMklmQLwBXQMb7CzIvz/Pl2fDYFMCAiW9/PGJoB/1gz9ppkpkyyKbThmzjNM+2ZZxu6zjd9KvM03WeZq49jNOmdfhp47uAKaTTtnf8NCgUwM5xeoykIKPKOkZi/DtP20hIlfLTYYykBP0q83Sdp20kYnGdjvN05HSaI0lzJIgXBf799BwJ1C15jiTPkWRGUuZIyhxJ4Vedp+s8XfVrjqTOkVRG0uZI2hwJkqK0OZI2RwJTlz5H0udIUOOI6eg0kBGAeXUrov0xoDEG7GKdLIct6xFtiLwvtj9xk4z8X9x91ngwKZ1n8G1l8sU+idkbCEr76RIOxmx2GnauypC3zuwNz2MTcJLnIihaJCrsZiWcjhQpO4iHxNRCcr0reTIGkX0hG1C6TiiluTFJbqDxsb2uU3DQXW0IZjEfcGgFQkhBIocN3hZUYJeiqPRAVM/pKPjR5qAkgt+2gY5d0ZE0QPbACviXTYez18N4GLap8lXy/ELgdOZX0R61g3ogPQjnXyTnlDxVvNqIhO5ppVnGGKlD7u1O0qmrfhfmh20bsGvJw7WDbACFHZa4xEdUqNA4YKLoRXoCvQgLJokQphfpptU1IJKXwMGUydJiPuAClRecsYOg26MKIziZ9QhOzqSbmh+zQCTR9aBXg6FpOEOv3aO4nuRQIMcUZXAlv1EJeuhbrIX9wbtpXT9chpI8sjr7Jq2IsJHxMHmFyD60IvsGxiTJuAGjN3TlTVvXlTQJe7Ft/AbyLrB1ceTaQT2427iA24tpNT0qH4uDeHB4pQynHrNIcdTA/nh8tVOwcgNWLj6YgJVbzlSQ4IrB6spm7rw880iuGmc2kxWB5o+X1c3TXsJhRPjsksnK0BUEtq4eSEqRxhPRATuQ3hX7ta4c/nVCUTdjU3EhVkaoGOvXDo4BKOMa4pfrOi5hl9yIA13zdt8L/L9fjOZ9ghz7/IB7+QL3f58HQZ4S5ZJvA/q3k5x2soNVWxWPGQLBbUVyA+WcYyKYbDLVUHxjHvbR8YU6v0+YHy+fZpdgkzQ4sXV/jFSTRcIdessKVArv3eJUXv4y8vQRE2mgsdnNkYKwqFqwRQfl4IC1cknVCbyR8oS0CLAMfOyS8n/Zf0ASBV9RORcrtQrJhKApdJEk97gOSLQDE7XJWHG1jW1/Voe7FXqsOTqorTkdEE+MQRECDCEAYKJk572FR8p8pCST1cwE5/BKuLnpwAQDophQjNnSkVT4uEqARlLgZ90FUO5TplYt2o2NO1ocyNOS4IgYNjoPrlHpfIvey2P2SGdE3d8NtVcUWxHUeDbiOdDK4D0w689XN5KeFMMQmXbAqZDHtaB04T6uEfrdHHBlK9XYgjgjyxmr9jTYMV0aMbA4
